version: 2
dependencies:
  cache_directories:
    - "~/docker-images"
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1
      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      - image: circleci/postgres:alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: sample
      - image: redis:alpine
    working_directory: /go/src/github.com/cryptopay-dev/yaga
    environment:
      TEST_REDIS_ADDR: localhost:6379
      TEST_DATABASE_ADDR: localhost:5432
      TEST_DATABASE_USER: postgres
      TEST_DATABASE_DATABASE: sample
      TEST_DATABASE_PASSWORD: postgres
      PGPASSWORD: postgres
      DEP_HASH: 31144e465e52ffbc0035248a10ddea61a09bf28b00784fd3fdd9882c8cbb2315
    steps:
      - checkout
      - run:
          name: Wait for db
          command: dockerize -wait tcp://${TEST_DATABASE_ADDR} -timeout 1m
      - run:
          name: Dep
          command: |
              curl -fsSL -o /go/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
              sha256sum /go/bin/dep | grep "${DEP_HASH}" || exit 1
              chmod +x /go/bin/dep
              dep ensure
      - run:
          name: Migrate
          command: |
              echo "Copy migrates"
              cp ./middlewares/auth/sample.sql 1512662685_sample.up.sql
              touch 1512662685_sample.down.sql
              echo "Run migration"
              go run migrate/cmd/main.go \
                  -a ${TEST_DATABASE_ADDR} \
                  -u ${TEST_DATABASE_USER} \
                  -p ${TEST_DATABASE_PASSWORD} \
                  -d ${TEST_DATABASE_DATABASE} \
                  -src ./ \
                  -t up
      # Add the Postgres binaries to the path.
      - run: go test -v ./...